### ISSUE TITLE
Working with packaged build?

### ISSUE THREAD

**Issue by TheOrestes** [Temaran/UE4RenderDocPlugin#18]
Hi Temaran,
Thanks a lot for this wonderful addition. RenderDoc is extremely helpful & by combining that with unreal editor you have helped tremendously. However, is there any reason why this doesn't work with final packaged builds? It seems that RenderDoc fails to recognize Unreal window itself. I have also asked the same thing to original author of Renderdoc. Or there is something very simple step that am ignoring? 
Your input will be super useful :)

Regards.

**Comment by Temaran** [comment]
Hello there!

Ive only really used the plugin in the editor, and I only really designed
it to run in there. Saying that however, just running renderdoc on built
games should work fine I think.
If its not recognizing the window, maybe it has something to do with child
windows (sometimes causes problems on windows).

Without seeing whats going on, I dont think I can be of that much help :(
I just came home from a month long vacation without much internet acces,
which is why this reply comes a bit late, but as soon as Ive gotten
everything at work sorted, I might have a go at this problem unless you
guys already solved it :)

Best regards,
Temaran

2016-08-25 8:54 GMT+02:00 Rupesh Mandke notifications@github.com:

**Comment by TheOrestes** [comment]
Hi Temaran,

Thanks for responding. I got in touch with baldurk himself & figured out the right way of attaching Unreal Packaged build window to Renderdoc. Here is the complete summary : https://github.com/baldurk/renderdoc/issues/338

So, I have now switched to vanilla renderdoc version as it suffice my requirements. Thanks for the wonderful plugin though :) 

Regards.

**Comment by Temaran** [comment]
Thanks for the link and I'm glad it worked out!
