### ISSUE TITLE
Plugin does not show up in Modules

### ISSUE THREAD

**Issue by inequation** [Temaran/UE4RenderDocPlugin#2]
Hi there,

I'm trying to integrate this plugin into our project. I've cloned this repo and put it into `Engine/Plugins`, and Unreal Build Tool builds it. It doesn't work, however, and it doesn't show up in the Window -> Developer -> Modules window.

Any tips on how I should go about debugging this?

**Comment by Temaran** [comment]
Hello!

Sorry for the late reply, I'm currently in Japan on parental leave and have
very sporadic internet access xD

It might have been the engine version, I just recently created a branch for
4.6, so if that is what you are using, it should work now.
Otherwise, I have seen it work when being added as an engine plugin, but
generally I would advise adding it as a project plugin as that is less
volatile.
This involves copying both plugin directories to your MYPROJECT/plugins/
folder.

I hope this solves your problem if you have not already :)

Best regards,
Temaran

2014-11-24 12:22 GMT+01:00 Leszek Godlewski notifications@github.com:

**Comment by inequation** [comment]
It started appearing at some point, issue is invalid. ;)
