### ISSUE TITLE
Capture does nothing in 4.8

### ISSUE THREAD

**Issue by inequation** [Temaran/UE4RenderDocPlugin#3]
Just like in the title. Debugging reveals that `RenderDocStartFrameCapture()` is called, but nothing actually happens. No log is written to `Saved/RenderDocCaptures`, as was the case in earlier engine versions.

Using RenderDoc 0.24.

**Comment by baldurk** [comment]
I think this is probably because of the renderdoc API change in 0.24 - StartFrameCapture expects the  ID3D11Device\* and HWND, not just the HWND. I'm not sure if the plugin checks the API version to see that it's the value it expects and bails out, that might explain that it's not capturing.

If you fix this by hand (you'd just need to get the ID3D11Device\* from UE4 and update renderdoc_app.h) then you'll also need to get a nightly build of renderdoc, because [this commit](https://github.com/baldurk/renderdoc/commit/237fdd773d146e4abace13851f49c4d40ad8d17f) fixes a bug present in 0.24 that means it won't recognise the device pointer normally because of vtable shenanigans (oops).

**Comment by Temaran** [comment]
oo, I'll try to have a look at this when I can. Super busy this week, but
hopefully I can take a bit of time for it :)
No promises though!

/Temaran

2015-06-08 14:19 GMT+02:00 Baldur Karlsson notifications@github.com:

**Comment by debaetsd** [comment]
If anybody is interested, I updated my [fork](https://github.com/debaetsd/UE4RenderDocPlugin) to work with UE 4.8.1 and renderdoc 0.24+ (nightly build, ef1dffba).

If I find the time this week, I'll clean it up and make a pull request ;)
