### ISSUE TITLE
Unreal 4.18.3 on Linux

### ISSUE THREAD

**Issue by dawgster** [Temaran/UE4RenderDocPlugin#34]
Hey I am having a similar issue as #33, however I am using Unreal engine on Ubuntu Linux. I dont see the icons in the editor,  even though i have provided [RenderDoc] BinaryPath=/home/jakub/renderdoc_1.0/renderdoc_1.0/bin/qrenderdoc in the DefaultGame.ini. I would appreciate a quick answer as I would really like to to take some pretty pictures for my thesis that is due next week.

Thank you for you time!

Jakub

**Comment by Temaran** [comment]
Are you using the engine integrated version?
You shouldn't have to provide the ini path manually, rather you should be prompted to find it with a file dialog when running the editor with the plugin loaded.

Have you activated the plugin in the plugin manager?

**Comment by dawgster** [comment]
Yes I am attempting to use the engine provided version. I activated it in the manager, restarted the editor but there was no prompt to be seen. Afterwards I tried adding the path manually but unfortunatly withou success.

**Comment by Temaran** [comment]
Hmm.

Well, having a look, it isn't super surprising that it doesn't work since it currently only whitelists Win32 and Win64 (have a look in the uplugin file).
I wonder if this is unneccessary though since I only really used platform independent functions. The arguments to those function do however use filters for windows (.exe).

It might be a really simple fix tbh, but since I don't have a unix dev machine, I can't really try it.
Feel free to do a pull request yourself to fix the problem and add unix :).

From what I can see with just a quick scan, I only think you need to change the whitelist spec as well as make a compilation branch for the dialog so you get proper suggestions for it to start working.

Best regards,
Temaran
